coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
    changes:
      default:
        informational: true

ignore:
  - "**/dist/**"
  - "**/coverage/**"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/index.ts"
  - "playground/**"

flags:
  core:
    paths:
      - packages/core/src/
    carryforward: true
  react:
    paths:
      - packages/react/src/
    carryforward: true
  plugin-textarea:
    paths:
      - packages/plugin-textarea/src/
    carryforward: true
  shiki-editor:
    paths:
      - packages/shiki-editor/src/
    carryforward: true
  testkit:
    paths:
      - packages/testkit/src/
    carryforward: true
