repository: konojunya/vimee/packages/core
coverage:
  paths:
    - coverage/lcov.info
  acceptable: current >= 80% && diff >= -5.0%
codeToTestRatio:
  code:
    - "src/**/*.ts"
    - "!src/**/*.test.ts"
    - "!src/index.ts"
  test:
    - "src/**/*.test.ts"
testExecutionTime:
  acceptable: current < 1min && diff < 1min
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
summary:
  enable: true
comment:
  if: is_pull_request
